# Generated by Django 5.1.5 on 2025-01-26 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
