# Generated by Django 5.1.5 on 2025-02-15 11:26

import django.db.models.deletion
import game.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_gamesession_id_delete_chat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameprogress',
            name='character',
        ),
        migrations.RemoveField(
            model_name='game',
            name='host',
        ),
        migrations.RemoveField(
            model_name='game',
            name='players',
        ),
        migrations.RemoveField(
            model_name='gameprogress',
            name='player',
        ),
        migrations.RemoveField(
            model_name='gameprogress',
            name='session',
        ),
        migrations.RemoveField(
            model_name='gamesession',
            name='host',
        ),
        migrations.RemoveField(
            model_name='gamesession',
            name='players',
        ),
        migrations.AlterField(
            model_name='friendship',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_friendships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_friendships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MusicRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('spotify_playlist_id', models.CharField(max_length=255)),
                ('room_id', models.CharField(default=game.models.generate_room_id, max_length=6, unique=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting for Users'), ('active', 'Active'), ('ended', 'Ended')], default='waiting', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_music_rooms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserInRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_in_room', to='game.musicroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music_rooms_joined', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'room')},
            },
        ),
        migrations.DeleteModel(
            name='Character',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='GameProgress',
        ),
        migrations.DeleteModel(
            name='GameSession',
        ),
    ]
