# Generated by Django 5.1.5 on 2025-02-15 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='high_score',
        ),
        migrations.AddField(
            model_name='customuser',
            name='spotify_access_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Spotify Access Token'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='spotify_refresh_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Spotify Refresh Token'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/', verbose_name='Profile Picture'),
        ),
        migrations.DeleteModel(
            name='Friendship',
        ),
    ]
