# Generated by Django 5.1.5 on 2025-02-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_high_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='spotify_access_token',
            field=models.CharField(max_length=255, null=True, verbose_name='Spotify Access Token'),
        ),
    ]
